name: rsan_torch
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==1.13.1
      - numpy<2
      - scipy
      - scikit-learn
      - opencv-python==4.5.5.64
      - imageio
      - tensorboard
      - tensorboardX
      - MedPy

